services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/uploads
    networks:
      - app-network
    environment:
      - WHISPER_MODEL=tiny #Puede ser tiny, base, small, medium, turbo, large-v2, large-v3
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - api  # Asegura que la API esté levantada antes de iniciar el frontend
    volumes:
      - ./web:/usr/share/nginx/html:ro  # Asegúrate de que los archivos de tu web se sirvan correctamente

networks:
  app-network:
    driver: bridge
