# Se usa una imagen de Nginx para servir archivos estáticos
FROM nginx:alpine

# Copia el archivo HTML a la carpeta de Nginx
COPY index.html /usr/share/nginx/html

# Exponer el puerto 80 para la web
EXPOSE 80